import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { ContextProvider } from "@/lib/provider";
import Sidebar from "@/components/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <main className="relative min-h-screen bg-background">
            <div className="grid h-full lg:grid-cols-5">
              <Sidebar className="sticky top-0 hidden h-screen lg:block" />
              <section className="col-span-3 mt-4 rounded-tl-3xl border-border bg-white lg:col-span-4 lg:border-l lg:border-t">
                <div className="p-8">{children}</div>
              </section>
            </div>
          </main>
        </ContextProvider>
      </body>
    </html>
  );
}
